# Generated by Django 3.1.5 on 2021-03-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('subscription', '0002_subscription_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='checkout.order'),
            preserve_default=False,
        ),
    ]
