# Generated by Django 3.1.5 on 2021-03-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210211_1255'),
        ('subscription', '0003_subscription_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
