# Generated by Django 3.1.5 on 2021-03-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('profiles', '0001_initial'),
        ('products', '0002_auto_20210211_1255'),
        ('subscription', '0006_auto_20210306_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='checkout.order'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='profiles.userprofile'),
        ),
    ]
